/*
 * This file was generated by the Gradle "init" task.
 */

rootProject.name = "MinecraftPrometheusExporter"
include(":core")
include(":MinecraftPrometheusExporter-paper")
include(":MinecraftPrometheusExporter-velocity")
project(":MinecraftPrometheusExporter-paper").projectDir = file("paper")
project(":MinecraftPrometheusExporter-velocity").projectDir = file("velocity")
