name: PrometheusExporter
version: '@project.version@'
authors:
  - 'Jim (AnEnragedPigeon)'
  - 'sldk'
main: de.sldk.mc.PrometheusExporter
loader: de.sldk.mc.PrometheusExporterLoader
website: sldk.de
api-version: '1.21.4'
